---

language: go

go:
  - '1.11.x'
  - '1.x'

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v ./... -coverprofile coverage.out

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile coverage.out -service=travis-ci
